name: Deploy QUEASARS to Pypi

on:
  # Allow the PyPI deployment to be triggered manually or by other workflows.
  workflow_dispatch:
  workflow_call:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pypi deployment"
  cancel-in-progress: false

jobs:
  # Build the project and publish to PyPI
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install pipx
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
      - name: Install poetry
        run: |
          pipx install poetry==1.7.0
      - name: Install dependencies
        run: |
          poetry install
      - name: Publish to PyPi
        env:
          TESTPYPITOKEN: ${{ secrets.TESTPYPITOKEN }}
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi "$TESTPYPITOKEN"
          poetry publish -r test-pypi --build