# This workflow runs on protected version tags. It runs the CI, checks the tag / workflow input version
# for consistency with the pyproject.toml version and then deploys to PYPI and GitHub pages.

name: QUEASARS Deployment

on:
  # Runs only on protected tags of the form vX.Y.Z
  push:
    tags: ['v[0-9].[0-9].[0-9]']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version in the form: vX.Y.Z'
        type: string
        required: true
      deploy_to_pypi:
        description: 'Deploy to PyPI.'
        type: boolean
        required: false
        default: true
      deploy_to_pages:
        description: 'Deploy to GitHub Pages.'
        type: boolean
        required: false
        default: true

concurrency:
  # Only let one deployment run at a time.
  group: "queasars deployment"
  cancel-in-progress: false

jobs:
  Check_Version_Consistency:
    # Check that the project version given by the tag / manual workflow input matches the pyproject.toml version
    name: Check Version Consistency
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.version != '' }}
        name: Check workflow version input
        shell: bash
        env:
          VERSION_INPUT: ${{ inputs.version }}
        run: |
          echo $VERSION_INPUT
          if [[ $VERSION_INPUT != @(v[0-9].[0-9].[0-9]) ]]; then exit 1; fi
          echo "VERSION=${VERSION_INPUT:1}" >> $GITHUB_ENV
      - if: ${{ inputs.version == '' }}
        name: Get tag version
        shell: bash
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          echo "VERSION=${TAG_NAME:1}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install pipx
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
      - name: Install poetry
        run: |
          pipx install poetry==1.7.0
      - name: Install dependencies
        run: |
          poetry install
      - name: Check tag / input version consistency with pyproject.toml
        shell: bash
        run: |
          echo "project version derived from tag / manual input: ${VERSION}"
          toml_version=$(poetry version --short)
          echo "project version from pyproject.toml ${toml_version}"
          if [[ $VERSION != $toml_version ]]; then exit 1; fi

  Run_CI:
    # Run the CI again before deploying.
    name: Run CI
    uses: ./.github/workflows/queasars_ci.yml

  Deploy_To_PyPI:
    # Only deploy to PyPI if both the project version is consistent and the CI is run successfully.
    name: Deploy to PyPI
    needs: [Check_Version_Consistency, Run_CI]
    if: ${{ inputs.deploy_to_pypi }}
    uses: ./.github/workflows/queasars_deploy_to_pypi.yml
    secrets: inherit

  Deploy_Documentation:
    # Only deploy to GitHub Pages if the deployment to PyPI succeeded.
    name: Deploy to Github Pages
    needs: Deploy_To_PyPI
    if: ${{ inputs.deploy_to_pages == '' || inputs.deploy_to_pages == true }}
    uses: ./.github/workflows/queasars_deploy_documentation.yml